### PR TITLE
Add Client Credentials Grant flow

### PR DESCRIPTION
**Pull request by oshliaer**
Issue: #82

### CODE REVIEW

**Comment by erickoledadevrel** [comment]
FYI, I am looking at this PR, but I think it calls into question some fundamental design choices in the library, so I'm thinking things through.

**Comment by oshliaer** [comment]
@erickoledadevrel , I think I chose a wrong way. I'd like to re-build it to another variant.

I think It needs to use new properties `app_key` and `app_secret` like `exchangeJwt`.

For an example
```js
 OAuth2.createService('drive')
      .setAppId('...')
      .setAppSecret('...')
```

**Comment by oshliaer** [comment]
I've changed the implementation, but left the idea.
There are new methods:
-  setConsumerKey
- setConsumerSecret
- setGrantType

setGrantType is necessary for [extension grants](https://tools.ietf.org/html/rfc6749#section-4.5).

**Comment by git38** [comment]
hey

**Comment by erickoledadevrel** [comment]
My apologies for leaving this in limbo for so long. I've adapted your work in #133, where I worked to centralize some of the logic and keep the implementation a bit more generic. Please take a look and let me know what you think. I'll close this PR.

**Pull request closed without merging**
