### PR TITLE
Allow to modify payload before send request for token

### PR DESCRIPTION
**Pull request by migace**
This change allow to modify payload before send request

### CODE REVIEW

**Comment by migace** [comment]
I signed it!

**Comment by erickoledadevrel** [comment]
This looks like a good fix, since the jsdoc does claim that we will use the return value. Why did you revert it?

**Comment by migace** [comment]
Hi ! ☺

I don’t understand why there is used this “tokenPayload” variable and yes, I thought that I should
change it – I had many problems with connection to non-google service.

After created this PR I rembered that objects in JS are passed by reference.
When you pass “payload” by reference to my custom function, I could overwrite any value by
“payload.sth = value”. After this think, I closed this PR 😉

Best regards,
Michael

Od: Eric Koleda <notifications@github.com>
Odpowiedź do: gsuitedevs/apps-script-oauth2 <reply@reply.github.com>
Data: poniedziałek, 29 kwietnia 2019 14:45
Do: gsuitedevs/apps-script-oauth2 <apps-script-oauth2@noreply.github.com>
DW: Michael Gacek <gacek.michael@outlook.com>, State change <state_change@noreply.github.com>
Temat: Re: [gsuitedevs/apps-script-oauth2] Allow to modify payload before send request for token (#181)


This looks like a good fix, since the jsdoc does claim that we will use the return value. Why did you revert it?

**Comment by erickoledadevrel** [comment]
Ya, the existing sample seems to be relying on that behavior, but it's
probably best to use the returned value. I'll make the fix myself, but
thanks for pointing it out!

**Pull request closed without merging**
