### PR TITLE
Create Docusign.gs

### PR DESCRIPTION
**Pull request by ianmurray1994**
Sample Auth for Creating an Envelope using a Template for DocuSign.

### CODE REVIEW

**Comment by erickoledadevrel** [comment]
Thanks for the contribution! It looks like you have a few lint errors though:

https://travis-ci.org/gsuitedevs/apps-script-oauth2/builds/648149531#L254

You can run `npm run lint` on your local repo to check for errors. Please fix those and then I can merge.

**Comment by ianmurray1994** [comment]
Updated the script and fixed necessary errors! Let me know if you need anything further to contribute.

**Comment by erickoledadevrel** [comment]
Thanks for the fixes! It looks like the linter doesn't catch indentation problems, and there are quite a few lines that are indented too much or too little. Could you do one more pass to correct this? We try to standardize on two-space indents.

**Comment by ianmurray1994** [comment]
Hi Erick,

I fixed the indenting! Apologies about that!

Thanks,
Ian

**Comment by erickoledadevrel** [comment]
Merged, thanks!

**Pull request merged**
